
services:
  dataservice:
    build: ./DataService
    container_name: dataservice
    ports:
      - "5004:5000"  
    volumes:
      - ./DataService/data.xlsx:/app/data.xlsx  
  frontend:
    build: ./Frontend       
    container_name: frontend    # navn på containeren til docker desktop
    ports:
      - "5003:5000"    # din pc 5003 -> containerport 5000
    volumes:
      - ./Frontend:/app  
    depends_on:
      - dataservice
